package com.mycompany.interfacestodos;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import clases.BaseDeDatos;
import clases.Usuario;

/**
 * @class muestra cuatro opciones que podemos realizar con el programa, que son
 * pasar a una interfaz para cargar los datos de un usuario, pasar a una
 * interfaz para crear un nuevo usuario, mostrar una interfaz para mostrar todos
 * los usuarios o pasar a otra interfaz para banear a un usuario. Todo depende
 * del botón que se pulse en la interfaz, dispone de otro botón que al ser
 * pulsado termina el programa.
 * @author Rafael Vegas
 * @date 02/12/2018
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    private BaseDeDatos b;
    private Usuario u;
    private InterfazIniciar in;
    /**
     * Creates new form InterfazInicio
     */
    public InterfazPrincipal() {
        initComponents();
        in = new InterfazIniciar();
        if (in.habilitarBaneo()) {
            habilitarBaneo();
        }
        if(in.habilitarCompras()){
            habilitarBaneo();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana1 = new javax.swing.JPanel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso a Datos");
        setBackground(new java.awt.Color(255, 51, 51));
        setIconImages(null);
        setLocation(new java.awt.Point(240, 100));
        setName("marco"); // NOI18N
        setUndecorated(true);

        ventana1.setBackground(new java.awt.Color(0, 0, 0));
        ventana1.setName("cerrar"); // NOI18N

        bt1.setBackground(new java.awt.Color(0, 0, 204));
        bt1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 255, 255));
        bt1.setText("Iniciar Sesión");
        bt1.setToolTipText("");
        bt1.setFocusable(false);
        bt1.setName("bt1"); // NOI18N
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setBackground(new java.awt.Color(255, 153, 51));
        bt2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 255, 255));
        bt2.setText("Comprar");
        bt2.setEnabled(false);
        bt2.setFocusable(false);
        bt2.setName("bt2"); // NOI18N
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProductos(evt);
            }
        });

        bt3.setBackground(new java.awt.Color(255, 255, 0));
        bt3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        bt3.setForeground(new java.awt.Color(255, 255, 255));
        bt3.setText("Mostrar Usuarios");
        bt3.setFocusable(false);
        bt3.setName("bt3"); // NOI18N
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt4.setBackground(new java.awt.Color(255, 0, 0));
        bt4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        bt4.setForeground(new java.awt.Color(255, 255, 255));
        bt4.setText("Banear");
        bt4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt4.setEnabled(false);
        bt4.setFocusable(false);
        bt4.setName("bt4"); // NOI18N
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.setActionCommand("");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Debes iniciar sesión para poder banear");

        bt5.setBackground(new java.awt.Color(51, 255, 51));
        bt5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        bt5.setForeground(new java.awt.Color(255, 255, 255));
        bt5.setText("Nuevo Usuario");
        bt5.setFocusable(false);
        bt5.setName("bt2"); // NOI18N
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Debes iniciar sesión como empresa para comprar");

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Quitar Baneo");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        //jButton2.setEnabled(false);
        jButton2.setFocusable(false);
        jButton2.setName("bt4"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventana1Layout = new javax.swing.GroupLayout(ventana1);
        ventana1.setLayout(ventana1Layout);
        ventana1Layout.setHorizontalGroup(
            ventana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventana1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(ventana1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(ventana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventana1Layout.createSequentialGroup()
                        .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventana1Layout.createSequentialGroup()
                        .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventana1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ventana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(85, 85, 85))
            .addGroup(ventana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventana1Layout.createSequentialGroup()
                    .addGap(435, 435, 435)
                    .addComponent(bt5, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addGap(374, 374, 374)))
        );
        ventana1Layout.setVerticalGroup(
            ventana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventana1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ventana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventana1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventana1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addGroup(ventana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(ventana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventana1Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ventana1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventana1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @function pasa a la interfaz de banear al pulsar el boton banear
     */
    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        InterfazBanear in = new InterfazBanear();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt4ActionPerformed

    /**
     * @function pasa a la interfaz de registro al pulsar el boton de registro
     */
    private void verProductos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProductos
        // TODO add your handling code here:
        InterfazCompras in = new InterfazCompras();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_verProductos

	
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
InterfazQuitarBaneo in = new InterfazQuitarBaneo();
        in.setVisible(true);
        this.dispose();
    }
	
    /**
     * @function pasa a la interfaz de mostrar todos los usuarios al pulsar el
     * botón de mostrar todos
     */
	 
	 
    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        InterfazMostrar in = new InterfazMostrar();
        in.setVisible(true);
        this.dispose();
        u = new Usuario();
        b = new BaseDeDatos(u);
        in.cargandoDatos();
    }//GEN-LAST:event_bt3ActionPerformed

    /**
     * @function pasa a la interfaz de iniciar sesion cuando se pulsa el botón
     * de iniciar sesión
     */
    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        InterfazIniciar in = new InterfazIniciar();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt1ActionPerformed

    /**
     * @function termina el programa cuando se pulsa el boton de la cruz roja
     * que está en la parte superior derecha de la interfaz.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @function pasa a la interfaz de registro al pulsar el boton de registro
     */
    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        InterfazRegistro in = new InterfazRegistro();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt5ActionPerformed



    /**
     * @function devuelve un array de caracteres en un String(se utiliza para el
     * método getPassword por que el getText está ya obsoleto).
     * @param contra el array de caracteres que contiene la contraseña
     * @return devuelve una cadena
     */
    protected static String clave(char[] contra) {
        String clave = "";
        for (int i = 0; i < contra.length; i++) {
            clave += contra[i];
        }
        return clave;
    }

    protected void habilitarBaneo() {
        bt4.setEnabled(true);
        jLabel1.setText("");
    }
    
    protected void habilitarCompras() {
        bt2.setEnabled(true);
        jLabel2.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel ventana1;
    // End of variables declaration//GEN-END:variables

}
